apiVersion: v1
kind: Service
metadata:
  labels:
    name: issm-api
  name: issm-api
spec:
  ports:
  - port: 8080
    name: http-api
    nodePort: 30080
  selector:
    app: issm-api
  type: NodePort
