# Copyright 2020 - 2022 IBM Corporation

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
#
# Important: this template can either run in stakeholder context or 3rd-party
#
################################################################################

#
# Parameters being used:
#
# service_owner: stakeholder name
# vsbName: blue-print name
# transaction_uuid: transaction uuid
# product_DID: PO global ID of the service being orchestrated
# sla_DID: SLA global ID of the SLA of the service
#
#
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Note: this name must be identical accross all domain operators
  name: orchestrate
spec:
  templates:
  - name: orchestrate
    dag:
      tasks:
      - name: get-domain-env
        templateRef:
          name: workflow-environment
          template: get-domain-env
        arguments:
          parameters:
          - name: domain
            # myself
            value: "{{workflow.parameters.resource_owner}}"
      
      - name: dummy-create-vsd
        dependencies: [get-domain-env]
        template: create-descriptor
        arguments:
          parameters:
          - name: vs_url
            value: "{{tasks.get-domain-env.outputs.parameters.vs_url}}"
          - name: tenant_name
            value: "{{workflow.parameters.service_owner}}"
          - name: vsbName
            value: "{{workflow.parameters.vsbName}}"
          - name: parameters
            value: "{{workflow.parameters.vsd_parameters}}"


      - name: dummy-create-vsi
        dependencies: [dummy-create-vsd]
        template: create-instance
        arguments:
          parameters:
          - name: vs_url
            value: "{{tasks.get-domain-env.outputs.parameters.vs_url}}"
          - name: tenant_name
            value: "{{workflow.parameters.service_owner}}"
          - name: vsd_id
            value: "{{tasks.dummy-create-vsd.outputs.parameters.vsd_id}}"
          - name: name
            value: "{{workflow.parameters.vsbName}}"
          - name: userdata
            value: "{{workflow.parameters.userdata}}"

      - name: dummy-poll
        dependencies: [dummy-create-vsi]
        template: poll
        arguments:
          parameters:
          - name: poll
            value: "true"
          - name: vs_url
            value: "{{tasks.get-domain-env.outputs.parameters.vs_url}}"
          - name: tenant_name
            value: "{{workflow.parameters.service_owner}}"
          - name: vsi_id
            value: "{{tasks.dummy-create-vsi.outputs.parameters.vsi_id}}"
          - name: jq_query
            value: ".status"
          - name: jq_query_value
            value: "INSTANTIATED"
          - name: timeout
            value: 10

      - name: dummy-create-vsi-fail
        dependencies: [dummy-poll]
        template: dummy-create-vsi-fail
        when: "{{tasks.dummy-poll.outputs.parameters.status}} == \"TIMEOUT\""
        arguments:
          parameters:
          - name: vsi_id
            value: "{{tasks.dummy-create-vsi.outputs.parameters.vsi_id}}"

      - name: dummy-create-vsi-success
        dependencies: [dummy-poll]
        template: dummy-create-vsi-success
        when: "{{tasks.dummy-poll.outputs.parameters.status}} != \"TIMEOUT\""
        arguments:
          parameters:
          - name: vsi_id
            value: "{{tasks.dummy-create-vsi.outputs.parameters.vsi_id}}"

  - name: dummy-create-vsi-success
    inputs:
      parameters:
      - name: vsi_id
    dag:
      tasks:
      - name: sla-event
        when: "\"{{workflow.parameters.sla_DID}}\" != \"\""
        templateRef:
          name: workflow-base
          template: produce
        arguments:
          parameters:
          - name: data
            value: |
              { "eventType": "new_SLA",
                "transactionID": "{{workflow.parameters.transaction_uuid}}",
                "productID": "{{workflow.parameters.product_DID}}",
                "SLAID": "{{workflow.parameters.sla_DID}}",
                "instanceID": "{{inputs.parameters.vsi_id}}",
                "place": {{workflow.parameters.place}},
                "kafka_ip": "{{workflow.parameters.kafka_ip}}", "kafka_port": "{{workflow.parameters.kafka_port}}",
                "topic": "isbp-topic-out"
              }
          - name: kafka_topic
            value: "isbp-topic"
          - name: kafka_ip
            value: "{{workflow.parameters.kafka_dl_ip}}"
          - name: kafka_port
            value: "{{workflow.parameters.kafka_dl_port}}"

      - name: publish-status
        templateRef:
          name: workflow-base
          template: produce
        arguments:
          parameters:
          - name: kafka_ip
            value: "{{workflow.parameters.kafka_ip}}"
          - name: kafka_port
            value: "{{workflow.parameters.kafka_port}}"

          - name: data
            value: |
              { "msg_id": "{{workflow.name}}",
                "vsi_id": "{{inputs.parameters.vsi_id}}",
                "status": "SUCCESS"
              }
          - name: kafka_topic
            value: "issm-in-{{workflow.parameters.service_owner}}"

      - name: sla-breach-data
        templateRef:
          name: workflow-base
          template: sla-breach-data
        arguments:
          parameters:
          - name: sla_breach
            value: "{{workflow.parameters.sla_breach}}"

      - name: sla-send-ack
        # do this only if in SLA violation context
        dependencies: [sla-breach-data]
        when: "{{tasks.sla-breach-data.outputs.parameters.applicable}} == true"
        templateRef:
          name: workflow-base
          template: produce
        arguments:
          parameters:
          - name: data
            value: |
              { "eventType": "new_SLA_ACK",
                "transactionID": "{{tasks.sla-breach-data.outputs.parameters.transaction_uuid}}",
                "productID": "{{tasks.sla-breach-data.outputs.parameters.product_DID}}",
                "status": "COMPLETED"
              }
          - name: kafka_topic
            value: "isbp-topic"
          - name: kafka_ip
            value: "{{workflow.parameters.kafka_dl_ip}}"
          - name: kafka_port
            value: "{{workflow.parameters.kafka_dl_port}}"


  - name: dummy-create-vsi-fail
    inputs:
      parameters:
      - name: vsi_id
    dag:
      tasks:
      - name: publish-status
        templateRef:
          name: workflow-base
          template: produce
        arguments:
          parameters:
          - name: kafka_ip
            value: "{{workflow.parameters.kafka_ip}}"
          - name: kafka_port
            value: "{{workflow.parameters.kafka_port}}"

          - name: data
            value: |
              { "msg_id": "{{workflow.name}}",
                "vsi_id": "{{inputs.parameters.vsi_id}}",
                "status": "FAIL"
              }
          - name: kafka_topic
            value: "issm-in-{{workflow.parameters.service_owner}}"

      - name: sla-breach-data
        templateRef:
          name: workflow-base
          template: sla-breach-data
        arguments:
          parameters:
          - name: sla_breach
            value: "{{workflow.parameters.sla_breach}}"

      - name: sla-send-ack
        # do this only if in SLA violation context
        dependencies: [sla-breach-data]
        when: "{{tasks.sla-breach-data.outputs.parameters.applicable}} == true"
        templateRef:
          name: workflow-base
          template: produce
        arguments:
          parameters:
          - name: data
            value: |
              { "eventType": "new_SLA_ACK",
                "transactionID": "{{tasks.sla-breach-data.outputs.parameters.transaction_uuid}}",
                "productID": "{{tasks.sla-breach-data.outputs.parameters.product_DID}}",
                "status": "COMPLETED"
              }
          - name: kafka_topic
            value: "isbp-topic"
          - name: kafka_ip
            value: "{{workflow.parameters.kafka_dl_ip}}"
          - name: kafka_port
            value: "{{workflow.parameters.kafka_dl_port}}"

      - name: fail
        dependencies: [publish-status, sla-send-ack]
        templateRef:
          name: workflow-base
          template: fail


  - name: create-descriptor
    # Create a new VSD from the given blueprint name
    #
    # Parameters:
    # vs_url: URL to vertical slicer service (str)
    # tenant_name: the name of the vertical tenant (str)
    # vsbName: the name of the blueprint VSD is created from
    # name: VSD name
    # parameters: qos parameters to be given to this VSD
    #
    # outputs:
    # vsd_id: vertical descriptor id    
    inputs:
      parameters:
      - name: vs_url
      - name: tenant_name
      - name: vsbName
      - name: parameters
    script:
      image: python:alpine3.6
      imagePullPolicy: IfNotPresent
      command: [python]
      source: |
        import random
        import sys

        sys.stdout.write('DUMMY Create descriptor..\n')

        vsd_id = str(random.randint(1, 1000))
        sys.stdout.write('DUMMY instantiate returned: %s \n' % vsd_id)

        with open('/tmp/id.txt', 'w') as f:
            f.write(str(vsd_id))
    outputs:
      parameters:
      - name: vsd_id
        valueFrom:
          path: /tmp/id.txt


  - name: create-instance
    # Create a new VSI
    #
    # Parameters:
    # vs_url: URL to vertical slicer service (str)
    # tenant_name: the name of the vertical tenant to create (str)
    # vsd_id: the id of the descriptor this VSI is created from (str)
    #
    # outputs:
    # vsi_id: vertical service instance id
    inputs:
      parameters:
      - name: vs_url
      - name: tenant_name
      - name: vsd_id
      - name: name
      - name: userdata
    script:
      image: python:alpine3.6
      imagePullPolicy: IfNotPresent
      command: [python]
      source: |
        import random
        import sys

        sys.stdout.write('DUMMY Create instance..\n')
        vsi_id = str(random.randint(1, 1000))
        sys.stdout.write('DUMMY instantiate returned: %s \n' % vsi_id)

        with open('/tmp/id.txt', 'w') as f:
            f.write(str(vsi_id))

    outputs:
      parameters:
      - name: vsi_id
        valueFrom:
          path: /tmp/id.txt


  - name: poll
    # Poll for some VSI attribute (in case poll=true) as denoted by by jq_query and jq_query_value.
    # timeout is relevant for polling only
    #
    # Parameters:
    # poll: whether or not to poll (boolean). If false, then skip polling
    # vs_url: URL to vertical slicer service (str)
    # tenant_name: the name of the vertical tenant (str)
    # vsi_id: VSI id (str)
    # jq_query: VSI attribute to poll/query (str in jq format)
    # jq_query_value: the conditional value of the attribute; applicable for polling mode (str)
    # timeout: polling timeout (seconds in integer)
    #
    # Return: TIMEOUT in case of timeout or the attribute value
    inputs:
      parameters:
      - name: poll
      - name: vs_url
      - name: tenant_name
      - name: vsi_id
      - name: jq_query
      - name: jq_query_value
      - name: timeout
    script:
      image: python:alpine3.6
      imagePullPolicy: IfNotPresent
      command: [python]
      source: |
        import time
        import sys

        timeout = "{{inputs.parameters.timeout}}"
        sys.stdout.write('DUMMY wait: %s \n' % str(timeout))
        time.sleep(int(timeout))
        with open('/tmp/status.txt', 'w') as f:
            f.write("INSTANTIATED")

    outputs:
      parameters:
      - name: status
        valueFrom:
          path: /tmp/status.txt
