apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: issm-argo
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - pods/exec
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: issm-argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: issm-argo
subjects:
- kind: ServiceAccount
  name: default
- kind: Group
  name: system:serviceaccounts:default
  apiGroup: rbac.authorization.k8s.io
