# Copyright 2020 - 2021 IBM Corporation

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  # Emulate SLA breach notification being sent over ISSM kafka topic isbp-topic-out
  # Refer to step send-sla-breach for notification payload details
  generateName: fire-sla-breach-
spec:
  entrypoint: handle
  imagePullSecrets:
  - name: myregistrykey
  arguments:
    parameters:
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # ISSM kafka
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: kafka_ip
      value: 172.28.3.196
    - name: kafka_port
      value: 9092

    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # payload attributes
    # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    - name: metric
      value: requests
    - name: datatime_violation
      value: "31-01-2022T06:00"
    - name: datatime_prediction
      value: "31-01-2022T05:55"

    - name: transaction_id
      value: 5f1da43fcc3c46809ce70b3186d0d2cd
    - name: product_id
      value: 3e922f24-01ec-4f83-8328-b69dc9ab8f8e
    - name: instance_id
      value: "012"
    - name: place
      value: |
        {
          "id": "9d6301ac-698c-4ed0-bd28-b0446b0b305c",
          "href": "http://172.28.3.126:31080/tmf-api/geographicAddressManagement/v4/geographicAddress/9d6301ac-698c-4ed0-bd28-b0446b0b305c",
          "city": "Barcelona",
          "country": "Spain",
          "locality": "Barcelona",
          "geographicLocation": {
            "id": "f17148e1-b874-4e2e-a81e-86738d0ee044",
            "name": "Barcelona i2CAT Area, Spain ",
            "geometryType": "string",
            "geometry": [
              {
                "id": "c45f6cc2-85af-4f64-95d8-25f9ba775fab",
                "x": "41.3879",
                "y": "2.1699",
                "z": "3388.0"
              }
            ]
          }
        }        

  templates:
  - name: handle
    steps:
    - - name: send-sla-breach
        # publish discovered resources for the optimizer to consume
        templateRef:
          name: workflow-base
          template: produce
        arguments:
          parameters:
          - name: data
            value: |
              {
                "breachPredictionNotification": {
                  "metric": "{{workflow.parameters.metric}}",
                  "datatimeViolation": "{{workflow.parameters.datatime_violation}}",
                  "datatimePrediction": "{{workflow.parameters.datatime_prediction}}",
                  "transactionID": "{{workflow.parameters.transaction_id}}",
                  "productID": "{{workflow.parameters.product_id}}",
                  "instanceID": "{{workflow.parameters.instance_id}}",
                  "place": {{workflow.parameters.place}}
                }
              }
          - name: kafka_topic
            value: isbp-topic-out
          - name: kafka_ip
            value: "{{workflow.parameters.kafka_ip}}"
          - name: kafka_port
            value: "{{workflow.parameters.kafka_port}}"
