apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: issm-kafka
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: issm-kafka
      eventName: intent
  triggers:
    - template:
        name: kafka-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                #
                # Workflow name is the event_uuid defined in the payload
                # (see event parameters below)
                #
                name: "OVERRIDE"
              spec:
                entrypoint: handlerequest
                imagePullSecrets:
                - name: myregistrykey
                arguments:
                  parameters:
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # ISSM kafka bus
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: kafka_ip
                    value: 1.2.3.4
                  - name: kafka_port
                    value: 9092

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Discovery service
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: discovery_ip
                    value: 1.2.3.4
                  - name: discovery_port
                    value: 80

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Slicer service
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: slicer_ip
                    value: 1.2.3.4

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Callback parameters
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: callback
                    value: OVERRIDE

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Payload parameters
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: operation
                    value: OVERRIDE

                  - name: category
                    value: OVERRIDE

                  - name: latitude
                    value: OVERRIDE
                  - name: longitude
                    value: OVERRIDE

                  - name: service_owner
                    value: OVERRIDE

                  - name: offered_price
                    value: OVERRIDE

                  - name: slice_segment
                    value: OVERRIDE

                  - name: qos_parameters
                    value: OVERRIDE

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # operation == submit_bp
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: resources
                    value: OVERRIDE

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Id of the transaction
                  # (N/A for submit_intent)
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: transaction_uuid
                    value: OVERRIDE
                templates:
                - name: handlerequest
                  steps:
                  - - name: submit-intent
                      # It is assumed that this is the starting point of the transaction
                      # meaning that event_uuid here is the transaction_uuid
                      template: submit-intent-flow
                      when: "{{workflow.parameters.operation}} == \"submit_intent\""

                  - - name: submit-bp
                      template: submit-bp-flow
                      when: "{{workflow.parameters.operation}} == \"submit_bp\""

                - name: submit-intent-flow
                  dag:
                    tasks:
                    - name: smart-discovery-application
                      template: smart-discovery-application
                      arguments:
                        parameters:
                        - name: service_ip
                          value: "{{workflow.parameters.discovery_ip}}"
                        - name: service_port
                          value: "{{workflow.parameters.discovery_port}}"
                        - name: category
                          value: "{{workflow.parameters.category}}"
                        - name: latitude
                          value: "{{workflow.parameters.latitude}}"
                        - name: longitude
                          value: "{{workflow.parameters.longitude}}"
                        - name: offered_price
                          value: "{{workflow.parameters.offered_price}}"

                    - name: send-resouces-to-optimizer
                      # publish discovered resources for the optimizer to consume
                      dependencies: [smart-discovery-application]
                      template: produce-message
                      arguments:
                        parameters:
                        - name: data
                          # note: transaction_uuid is the event_uuid passed to this flow
                          value: |
                            { "event_uuid": "{{workflow.name}}", "transaction_uuid": "{{workflow.name}}",
                              "resources": [{{tasks.smart-discovery-application.outputs.result}}],
                              "callback": {{workflow.parameters.callback}}, "service_owner": "{{workflow.parameters.service_owner}}",
                              "category": "{{workflow.parameters.category}}", "qos_parameters": "{{workflow.parameters.qos_parameters}}" }
                        - name: kafka_topic
                          value: "issm-optimizer"

                - name: submit-bp-flow
                  dag:
                    tasks:
                    - name: acquire
                      # invokes acquire template for every entry in resources list
                      # waits for them to succeed and publishes status success for the
                      # service owner to consume
                      template: acquire
                      arguments:
                        parameters:
                        - name: offer_id
                          value: "{{item.id}}"
                      withParam: "{{workflow.parameters.resources}}"

                    - name: resource-vsb
                      dependencies: [acquire]
                      templateRef:
                        name: workflow-base
                        template: jq-script
                      arguments:
                        parameters:
                        - name: json_str
                          value: "{{workflow.parameters.resources}}"
                        - name: jq_query
                          value: '.[0].VSB'
  
                    - name: resource-segment
                      dependencies: [acquire]
                      templateRef:
                        name: workflow-base
                        template: jq-script
                      arguments:
                        parameters:
                        - name: json_str
                          value: "{{workflow.parameters.resources}}"
                        - name: jq_query
                          value: '.[0].slice_segment'


                    - name: slicer-create-group
                      dependencies: [resource-vsb, resource-segment]
                      templateRef:
                        name: workflow-slice
                        template: create-group
                      arguments:
                        parameters:
                        - name: slicer_ip
                          value: "{{workflow.parameters.slicer_ip}}"
                        - name: group_name
                          value: "5gzorro"

                    - name: slicer-create-tenant
                      dependencies: [slicer-create-group]
                      templateRef:
                        name: workflow-slice
                        template: create-tenant
                      arguments:
                        parameters:
                        - name: slicer_ip
                          value: "{{workflow.parameters.slicer_ip}}"
                        - name: group_name
                          value: "5gzorro"
                        - name: tenant_name
                          value: "{{workflow.parameters.service_owner}}"

                    - name: slicer-create-vsb
                      dependencies: [slicer-create-tenant]
                      templateRef:
                        name: workflow-slice
                        template: create-descriptor
                      arguments:
                        parameters:
                        - name: slicer_ip
                          value: "{{workflow.parameters.slicer_ip}}"
                        - name: tenant_name
                          value: "{{workflow.parameters.service_owner}}"
                        - name: blueprint_name
                          # VSB attr in offer
                          value: "{{tasks.resource-vsb.outputs.result}}"
                        - name: name
                          # VSB-slice_segment attr in offer
                          value: "{{tasks.resource-vsb.outputs.result}}-{{tasks.resource-segment.outputs.result}}"
                        - name: parameters
                          value: "{{workflow.parameters.qos_parameters}}"

                - name: smart-discovery-application
                  inputs:
                    parameters:
                    - name: service_ip
                    - name: service_port
                    - name: category
                    - name: latitude
                    - name: longitude
                    - name: offered_price
                  script:
                    image: docker.pkg.github.com/5gzorro/issm/python:alpine3.6-kafka-v0.1
                    command: [python]
                    source: |
                      import json
                      import requests
                      import sys

                      headers = {'Content-Type': 'application/json'}
                      r = requests.get("http://{{inputs.parameters.service_ip}}:{{inputs.parameters.service_port}}/discoveroffer/{{inputs.parameters.offered_price}}"
                          "lat{{inputs.parameters.latitude}}long{{inputs.parameters.longitude}}computeandvirtual{{inputs.parameters.category}}",
                          headers=headers)
                      # return first offer
                      json.dump(r.json()[0], sys.stdout)

                - name: acquire
                  # acquire is devided into two sub-tasks:
                  # 1. the acquire operation itself
                  # 2. branch to inspect acquire status and either fail the flow
                  # or proceed as normal
                  inputs:
                    parameters:
                    - name: offer_id
                  steps:
                    - - name: acquire-resource
                        template: acquire-simulator
                        arguments:
                          parameters:
                          - name: offer_id
                            value: "{{inputs.parameters.offer_id}}"

                    - - name: callback-acquire-fail
                        templateRef:
                          name: workflow-base
                          template: callback
                        when: "{{steps.acquire-resource.outputs.parameters.status}} == \"FAIL\""
                        arguments:
                          parameters:
                          - name: callback
                            value: "{{workflow.parameters.callback}}"
                          - name: data
                            value: |
                              { "event_uuid": "{{workflow.name}}", "transaction_uuid": "{{workflow.parameters.transaction_uuid}}", "status": "fail", "offer_id": "{{inputs.parameters.offer_id}}" }
                    - - name: fail-flow
                        template: fail
                        when: "{{steps.acquire-resource.outputs.parameters.status}} == \"FAIL\""

                - name: acquire-simulator
                  # simulate a resource purchase with a return of a
                  # fail/success status
                  inputs:
                    parameters:
                    - name: offer_id
                  script:
                    image: python:alpine3.6
                    command: [python]
                    source: |
                      import json
                      import random
                      import sys
                      status = "acquire_success"
                      json.dump({"offer_id": "{{inputs.parameters.offer_id}}", "status": status}, sys.stdout)
                      with open("/tmp/status.txt", "a") as myfile:
                          myfile.write(status)
                  outputs:
                    parameters:
                    - name: status
                      valueFrom:
                        path: /tmp/status.txt

                - name: fail
                  script:
                    image: debian:9.4
                    command: [bash]
                    source: |
                      exit 123

                - name: produce-message
                  inputs:
                    parameters:
                    - name: data
                    - name: kafka_topic
                  steps:
                    - - name: return-result
                        templateRef:
                          name: workflow-base
                          template: produce
                        arguments:
                          parameters:
                          - name: kafka_topic
                            value: "{{inputs.parameters.kafka_topic}}"
                          - name: kafka_ip
                            value: "{{workflow.parameters.kafka_ip}}"
                          - name: kafka_port
                            value: "{{workflow.parameters.kafka_port}}"
                          - name: data
                            value: "{{inputs.parameters.data}}"

          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.event_uuid
              dest: metadata.name

            - src:
                dependencyName: test-dep
                dataKey: body.callback
                value: DEFAULT
              dest: spec.arguments.parameters.5.value

            - src:
                dependencyName: test-dep
                dataKey: body.operation
              dest: spec.arguments.parameters.6.value

            - src:
                dependencyName: test-dep
                dataKey: body.category
                value: DEFAULT
              dest: spec.arguments.parameters.7.value

            - src:
                dependencyName: test-dep
                dataKey: body.latitude
                value: DEFAULT
              dest: spec.arguments.parameters.8.value

            - src:
                dependencyName: test-dep
                dataKey: body.longitude
                value: DEFAULT
              dest: spec.arguments.parameters.9.value

            - src:
                dependencyName: test-dep
                dataKey: body.service_owner
                value: DEFAULT
              dest: spec.arguments.parameters.10.value

            - src:
                dependencyName: test-dep
                dataKey: body.offered_price
                value: DEFAULT
              dest: spec.arguments.parameters.11.value

            - src:
                dependencyName: test-dep
                dataKey: body.slice_segment
                value: DEFAULT
              dest: spec.arguments.parameters.12.value

            - src:
                dependencyName: test-dep
                dataKey: body.qos_parameters
                value: DEFAULT
              dest: spec.arguments.parameters.13.value

            - src:
                dependencyName: test-dep
                dataKey: body.resources
                value: DEFAULT
              dest: spec.arguments.parameters.14.value

            - src:
                dependencyName: test-dep
                dataKey: body.transaction_uuid
                value: DEFAULT
              dest: spec.arguments.parameters.15.value
