# Copyright 2020 – 2021 IBM Corporation

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#
# Common sensor that invokes a workflow locally on the operator premises
#
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: issm-branch
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      # connects to platform bus
      eventSourceName: issm-kafka
      eventName: intent
  triggers:
    - template:
        name: kafka-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                #
                # Workflow name is the event_uuid defined in the payload
                # (see event parameters below)
                #
                name: "OVERRIDE"
                labels:
                  #
                  # transaction_uuid lable contains the transaction uuid of
                  # bussiness flow. NOTE: there could be several instances with
                  # a same transaction uuid
                  #
                  transaction_uuid: OVERRIDE
              spec:
                entrypoint: handlerequest
                imagePullSecrets:
                - name: myregistrykey
                - name: 5gzorroregistrykey
                arguments:
                  parameters:
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # ISSM kafka bus
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: kafka_ip
                    value: 172.28.3.196
                  - name: kafka_port
                    value: 9092

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # DL kafka bus
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: kafka_dl_ip
                    value: 172.28.3.196
                  - name: kafka_dl_port
                    value: 9092

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Discovery service
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: discovery_ip
                    value: 172.28.3.42
                  - name: discovery_port
                    value: 32000

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Slicer service
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: nsso_ip
                    # service name to be used by the local issm instance
                    value: vs
                  - name: nsso_port
                    value: 8082

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Payload parameters
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: operation
                    value: OVERRIDE

                  - name: sub_operation
                    value: OVERRIDE

                  - name: category
                    value: OVERRIDE

                  - name: latitude
                    value: OVERRIDE
                  - name: longitude
                    value: OVERRIDE

                  - name: service_owner
                    value: OVERRIDE

                  - name: service_owner_target
                    # target mno to extend slice/service
                    # (applicable for symetric orchestration)
                    value: OVERRIDE

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Range e.g. 1200-1400
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: requested_price
                    value: OVERRIDE

                  - name: resourceSpecCharacteristic
                    value: OVERRIDE

                  - name: qos_parameters
                    value: OVERRIDE

                  - name: resources
                    value: OVERRIDE

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Id of the transaction
                  # (N/A for submit_intent)
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: transaction_uuid
                    value: OVERRIDE

                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  # Id of the existing service
                  # to extend
                  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  - name: service_id
                    value: OVERRIDE

                  - name: product_id
                    value: OVERRIDE
                  - name: resource_id
                    value: OVERRIDE
                  - name: resource_vsb
                    value: OVERRIDE


                templates:
                - name: handlerequest
                  steps:
                  - - name: submit
                      # This is the starting point of the transaction
                      # meaning that event_uuid here is the transaction_uuid
                      templateRef:
                        name: submit-template
                        template: handle-submit
                      when: "{{workflow.parameters.operation}} == \"submit\""

          parameters:
            - src:
                #
                # event_uuid is treated as an instance uuid for this
                # flow instance
                dependencyName: test-dep
                dataKey: body.event_uuid
              dest: metadata.name

            - src:
                #
                # transaction_uuid is treated as the whole business transaction
                # that can contain several flows (i.e. several event_uuids)
                #
                dependencyName: test-dep
                dataKey: body.transaction_uuid
              dest: metadata.labels.transaction_uuid

            - src:
                dependencyName: test-dep
                dataKey: body.operation
              dest: spec.arguments.parameters.8.value

            - src:
                dependencyName: test-dep
                dataKey: body.operation
              dest: metadata.labels.operation

            - src:
                dependencyName: test-dep
                dataKey: body.sub_operation
                value: DEFAULT
              dest: spec.arguments.parameters.9.value

            - src:
                dependencyName: test-dep
                dataKey: body.category
                value: DEFAULT
              dest: spec.arguments.parameters.10.value

            - src:
                dependencyName: test-dep
                dataKey: body.latitude
                value: DEFAULT
              dest: spec.arguments.parameters.11.value

            - src:
                dependencyName: test-dep
                dataKey: body.longitude
                value: DEFAULT
              dest: spec.arguments.parameters.12.value

            - src:
                dependencyName: test-dep
                dataKey: body.service_owner
                value: DEFAULT
              dest: spec.arguments.parameters.13.value

            - src:
                dependencyName: test-dep
                dataKey: body.service_owner_target
                value: DEFAULT
              dest: spec.arguments.parameters.14.value

            - src:
                dependencyName: test-dep
                dataKey: body.requested_price
                value: DEFAULT
              dest: spec.arguments.parameters.15.value

            - src:
                dependencyName: test-dep
                dataKey: body.resourceSpecCharacteristic
                value: DEFAULT
              dest: spec.arguments.parameters.16.value

            - src:
                dependencyName: test-dep
                dataKey: body.qos_parameters
                value: DEFAULT
              dest: spec.arguments.parameters.17.value

            - src:
                dependencyName: test-dep
                dataKey: body.resources
                value: DEFAULT
              dest: spec.arguments.parameters.18.value

            - src:
                dependencyName: test-dep
                dataKey: body.transaction_uuid
                value: notapplicable
              dest: spec.arguments.parameters.19.value

            - src:
                dependencyName: test-dep
                dataKey: body.service_id
                value: DEFAULT
              dest: spec.arguments.parameters.20.value

            - src:
                dependencyName: test-dep
                dataKey: body.product_id
                value: DEFAULT
              dest: spec.arguments.parameters.21.value

            - src:
                dependencyName: test-dep
                dataKey: body.resource_id
                value: DEFAULT
              dest: spec.arguments.parameters.22.value

            - src:
                dependencyName: test-dep
                dataKey: body.resource_vsb
                value: DEFAULT
              dest: spec.arguments.parameters.23.value
