# Copyright 2020 - 2022 IBM Corporation

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: snfvo-ota-composite
spec:
  templates:
  - name: instantiate
    steps:
    - - name: instantiate-service
        when: "{{workflow.parameters.sub_operation}} == \"INSTANTIATE_SERVICE\""
        template: instantiate-service


  - name: instantiate-service
    dag:
      tasks:
      - name: get-order-from-catalog
        templateRef:
          name: workflow-catalog
          template: get-order-from-catalog
        arguments:
          parameters:
          - name: order_id
            value: "{{workflow.parameters.order_id}}"

      - name: trigger-instantiate
        dependencies: [get-order-from-catalog]
        template: trigger-instantiate
        arguments:
          parameters:
          - name: related_party
            value: "{{tasks.get-order-from-catalog.outputs.parameters.related_party}}"
          - name: order_id
            value: |
              [
                {"uuid": "37f313d5-f3ba-4b34-8ddf-12ce7bcb52c6"},
                {"uuid": "76d0d91c-37f8-43d9-bb63-3ac6a4373d49", "main": "true"}
              ]
          - name: snfvo_data
            value: |
              {
                "userdata_edge": {
                  "cp_address.upf_e.n4_net.cp_n4": "192.168.162.3",
                  "cp_address.upf_e.vpn_net.cp_int": "192.168.161.2",
                  "cp_address.gw.vpn_net.cp_int": "192.168.161.9",
                  "cp_address.upf_e.app_net.cp_app": "192.168.161.19",
                  "cp_address.edge_app.app_net.cp_app": "192.168.161.18"
                },
                "userdata_core": {
                  "cp_address.core.n4_net.cp_n4": "192.168.162.5",
                  "cp_address.ueransim.n4_net.cp_n4": "192.168.162.7",
                  "cp_address.core.vpn_net_core.cp_int": "192.168.161.50",
                  "cp_address.gw.vpn_net_core.cp_int": "192.168.161.51",
                  "cp_address.ueransim.vpn_net_core.cp_int": "192.168.161.52"
                },
                "vsd_parameters": {
                  "users": "1000"
                }
              }

  - name: trigger-instantiate
    inputs:
      parameters:
      - name: related_party
      # list of orders ({uuid,main},..)
      - name: order_id
      - name: snfvo_data
    steps:
      - - name: event-uuid
          templateRef:
            name: workflow-base
            template: event-uuid
      - - name: publish-to-instantiate
          templateRef:
            name: workflow-base
            template: publish-on-kafka
          arguments:
            parameters:
            - name: data
              # note: service_owner in this sense is the owner of this order's offer (e.g. operator-c)
              # where it will perform the actual orchestration/stiching
              # Note: for now outer order_id should match the main one above
              value: |
                {
                  "issm": "true", "_operation": "instantiate",
                  "service_owner": "{{inputs.parameters.related_party}}",
                  "operation": "order",
                  "sub_operation": "PRE_ONBOARD_INSTANTIATE",
                  "order_id": "38b01c74-5e38-4024-afb5-c603620496f3",
                  "intent": {
                    "transaction_uuid": "{{workflow.parameters.transaction_uuid}}",
                    "event_uuid": "{{steps.event-uuid.outputs.result}}",
                    "service_owner": "{{inputs.parameters.related_party}}",
                    "operation": "instantiate", "sub_operation": "API",
                    "order_id": {{inputs.parameters.order_id}},
                    "snfvo_data": {{inputs.parameters.snfvo_data}}
                  }
                }
            - name: kafka_topic
              # Important: forward to aux so that snfvo is auto onboarded
              value: "issm-aux-{{inputs.parameters.related_party}}"

  - name: scaleout
    dag:
      tasks:
      - name: success
        templateRef:
          name: workflow-base
          template: success
