# Copyright 2020 - 2022 IBM Corporation

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: snfvo-vcdn-on-slice
spec:
  templates:
  - name: instantiate
    steps:
    - - name: instantiate-service
        when: "{{workflow.parameters.sub_operation}} == \"INSTANTIATE_SERVICE\""
        template: instantiate-service
    - - name: optimizer-response
        when: "{{workflow.parameters.sub_operation}} == \"BEST_OFFER_SELECTION\""
        template: optimizer-response

  - name: instantiate-service
    dag:
      tasks:
      - name: get-order-from-catalog
        templateRef:
          name: workflow-catalog
          template: get-order-from-catalog
        arguments:
          parameters:
          - name: order_id
            value: "{{workflow.parameters.order_id}}"

      - name: build-discovery-query
        dependencies: [get-order-from-catalog]
        templateRef:
          name: workflow-discovery
          template: build-intent-query
        arguments:
          parameters:
          - name: category
            value: Edge

          - name: place
            value: "{{workflow.parameters.place}}"
          - name: cpu
            value: ""
          - name: mem
            value: ""
          - name: mem_unit
            value: ""
          - name: storage
            value: ""
          - name: storage_unit
            value: ""

      - name: discover-edges
        templateRef:
          name: workflow-discovery
          template: srds-service
        dependencies: [build-discovery-query]
        arguments:
          parameters:
          - name: srsd_url
            value: "{{workflow.parameters.srsd_url}}"
          - name: intent_query
            value: "{{tasks.build-discovery-query.outputs.result}}"

      - name: prepare-request-to-optimizer
        #dependencies: [build-discovery-query]
        dependencies: [discover-edges]
        templateRef:
          name: workflow-topology
          template: mock-optimizer-output
        arguments:
          parameters:
          - name: resources
            value: "{{tasks.discover-edges.outputs.result}}"
#            value: |
#              [{"todo": "replace until SRSD is fixed"}]
          - name: app_topology
            value: "{{workflow.parameters.app_topology}}"
  
      - name: send-edges-to-optimizer
        # simulates interaction with ISSM-O
        dependencies: [prepare-request-to-optimizer]
        templateRef:
          name: workflow-base
          template: publish-on-kafka
        arguments:
          parameters:
          - name: data
            value: |
              { "transaction_uuid": "{{workflow.parameters.transaction_uuid}}",
                "topic": "issm-in-{{workflow.parameters.service_owner}}", 
                "category": "{{workflow.parameters.category}}",
                "resources": {{tasks.discover-edges.outputs.result}},
                "operation": "instantiate", "sub_operation": "BEST_OFFER_SELECTION",
                "service_owner": "{{workflow.parameters.service_owner}}",
                "order_id": "{{workflow.parameters.order_id}}",
                "catalogue_url": "{{workflow.parameters.catalogue_url}}",
                "trmf_url": "{{workflow.parameters.trmf_url}}",
                "issm_api_url": "{{workflow.parameters.issm_api_url}}",
                "domain_related_party_did": "{{workflow.parameters.service_owner_did}}",
                "name": "{{tasks.get-order-from-catalog.outputs.parameters.name}}",
                "snfvo_data": {{workflow.parameters.snfvo_data}},
                "kafka": "{{workflow.parameters.kafka}}",
                "app_topology": {{workflow.parameters.app_topology}},
                "serviceSpecification_resourceSpecification": {{tasks.get-order-from-catalog.outputs.parameters.serviceSpecification_resourceSpecification}},
                "optimizer_output": {{tasks.prepare-request-to-optimizer.outputs.parameters.optimizer_output}}
              }
          - name: kafka_topic
            value: issm-optimizer

# optimizer_output e.g.:
# [{'index': 0, 'selected_offer': '...', 'mapped_function': 'upf'},
# {'index':  1, 'selected_offer': '...', 'mapped_function': 'core'},
# {'index':  2, 'selected_offer': '...', 'mapped_function': 'upf'},
# {'index':  3, 'selected_offer': '...', 'mapped_function': 'app'},
# {'index':  4, 'selected_offer': '...', 'mapped_function': 'app'}]
  - name: optimizer-response
    dag:
      tasks:
      - name: core-entry
        template: core-entry
        arguments:
          parameters:
          - name: entries
            value: "{{workflow.parameters.optimizer_output}}"

      - name: handle-core
        dependencies: [core-entry]
        template: handle-placement-entry
        arguments:
          parameters:
          - name: entry
            value: "{{tasks.core-entry.outputs.parameters.entry}}"

      - name: loop-edges
        # deploy in parallel (loop) all other functions excluding core
        dependencies: [handle-core]
        template: handle-placement-entry
        arguments:
          parameters:
          - name: entry
            value: "{{item}}"
        withParam: "{{tasks.core-entry.outputs.parameters.entries}}"

  - name: handle-placement-entry
    # Note: these are 'flattened JSON': true, null, ..
    inputs:
      parameters:
      - name: entry
    dag:
      tasks:
      - name: selected-offer
        template: from-key-flatten
        arguments:
          parameters:
          - name: key
            value: selected_offer
          - name: json_str
            value: |
              {{inputs.parameters.entry}}

      - name: index
        template: from-key-flatten
        arguments:
          parameters:
          - name: key
            value: index
          - name: json_str
            value: |
              {{inputs.parameters.entry}}

      - name: mapped-function
        templateRef:
          name: workflow-base
          template: from-key
        arguments:
          parameters:
          - name: key
            value: mapped_function
          - name: json_str
            value: |
              {{inputs.parameters.entry}}

      - name: print-selected-offer
        dependencies: [selected-offer]
        templateRef:
          name: workflow-base
          template: jq-script
        arguments:
          parameters:
          - name: json_str
            value: "{{tasks.selected-offer.outputs.result}}"
          - name: jq_query
            value: '.'

      - name: selected-offer-attributes
        dependencies: [selected-offer]
        templateRef:
          name: workflow-discovery
          template: resource-attributes
        arguments:
          parameters:
          - name: resource
            value: "{{tasks.selected-offer.outputs.result}}"

#      - name: acquire
#        dependencies: [selected-offer-attributes, print-selected-offer]
#        templateRef:
#          name: workflow-catalog
#          template: acquire
#        arguments:
#          parameters:
#          - name: resource_name
#            value: "{{tasks.selected-offer-attributes.outputs.parameters.name}}"
#          - name: resource_category
#            value: "{{tasks.selected-offer-attributes.outputs.parameters.category}}"
#          - name: resource_id
#            value: "{{tasks.selected-offer-attributes.outputs.parameters.id}}"
#          - name: operator_id_seller
#            value: "{{tasks.selected-offer-attributes.outputs.parameters.related_party}}"
#          - name: operator_id_did_seller
#            value: "{{tasks.selected-offer-attributes.outputs.parameters.related_party_did}}"
#
#          - name: operator_id_buyer
#            value: "{{workflow.parameters.service_owner}}"
#          - name: operator_id_did_buyer
#            value: "{{workflow.parameters.service_owner_did}}"
#
#          - name: resource_did
#            value: "{{tasks.selected-offer-attributes.outputs.parameters.did}}"

      - name: userdata
        dependencies: [mapped-function, index]
        template: userdata
        arguments:
          parameters:
          - name: mapped_function
            value: "{{tasks.mapped-function.outputs.result}}"
          - name: index
            value: "{{tasks.index.outputs.result}}"
          - name: snfvo_data
            value: |
              {{workflow.parameters.snfvo_data}}


      - name: trigger-orchestration
        # dependencies: [acquire, userdata]
        dependencies: [userdata, selected-offer-attributes]
        templateRef:
          name: workflow-orchestrator
          template: trigger-orchestration
        arguments:
          parameters:
          - name: resource_owner
            # domain's orchestrator
            value: "{{tasks.selected-offer-attributes.outputs.parameters.related_party}}"

          - name: vsbName
            # possible values: 'core', 'upf' or 'app'
            value: "{{tasks.mapped-function.outputs.result}}"

          - name: userdata
            value: "{{tasks.userdata.outputs.parameters.userdata}}"

          - name: vsd_parameters
            value: "{ }"

      - name: wait-for-status
        dependencies: [trigger-orchestration]
        templateRef:
          name: workflow-base
          template: consume
        arguments:
          parameters:
          - name: kafka
            value: "{{workflow.parameters.kafka}}"
          - name: kafka_topic
            value: "issm-in-{{workflow.parameters.service_owner}}"
          - name: msg_id
            value: "{{tasks.trigger-orchestration.outputs.parameters.event_uuid}}"

      - name: get-instance-id
        dependencies: [wait-for-status]
        templateRef:
          name: workflow-base
          template: from-key
        arguments:
          parameters:
          - name: key
            value: vsi_id
          - name: json_str
            value: |
              {{tasks.wait-for-status.outputs.parameters.payload}}

#      - name: update-order
#        dependencies: [get-instance-id]
#        templateRef:
#          name: workflow-catalog
#          template: update-order-instance-id
#        # in any case, persist instanceId
#        arguments:
#          parameters:
#          - name: transaction_uuid
#            value: "{{workflow.parameters.transaction_uuid}}"
#          - name: order_id
#            # the main NetworkService order
#            value: "{{workflow.parameters.order_id}}"
#          - name: main
#            value: "true"
#          - name: instance_id
#            value: "{{tasks.get-instance-id.outputs.result}}"
#          - name: related_party
#            value: "{{tasks.selected-offer-attributes.outputs.parameters.related_party}}"

  - name: scaleout
    dag:
      tasks:
      - name: success
        templateRef:
          name: workflow-base
          template: success

  - name: from-key-flatten
    # Temporary step to return a flattened JSON rather than a python dictionary
    # Note: it works only when result is a json
    inputs:
      parameters:
      - name: key
      - name: json_str
    script:
      image: python:alpine3.6
      imagePullPolicy: IfNotPresent
      command: [python]
      source: |
        import json

        print(json.dumps({{inputs.parameters.json_str}}['{{inputs.parameters.key}}']))


  - name: core-entry
    # Retrieve 'core' placement entry from the placement list, returning back
    # the list excluding that
    inputs:
      parameters:
      - name: entries
    script:
      image: python:alpine3.6
      imagePullPolicy: IfNotPresent
      command: [python]
      source: |
        import json
        import sys

        def find(l, predicate):
            """
            util method
            """
            results = [x for x in l if predicate(x)]
            return results[0] if len(results) > 0 else None

        entries = {{inputs.parameters.entries}}
        sys.stdout.write('entries: "%s" \n' % entries)

        entry = find(entries, lambda e: e.get('mapped_function', '') == 'core')
        if not entry:
            raise Exception("*** Unable to find 'core' entry ***")

        entries.remove(entry)
        with open('/tmp/entry.txt', 'w') as f:
            json.dump(entry, f)
        with open('/tmp/entries.txt', 'w') as f:
            json.dump(entries, f)

    outputs:
      parameters:
      - name: entry
        valueFrom:
          path: /tmp/entry.txt
      - name: entries
        # placement entries without the core
        valueFrom:
          path: /tmp/entries.txt

  - name: userdata
    inputs:
      parameters:
      - name: mapped_function
      - name: index
      - name: snfvo_data
    script:
      image: python:alpine3.6
      imagePullPolicy: IfNotPresent
      command: [python]
      source: |
        import json
        import sys

        mapped_function = "{{inputs.parameters.mapped_function}}"
        sys.stdout.write('mapped_function: "%s" \n' % mapped_function)

        index = int("{{inputs.parameters.index}}")
        sys.stdout.write('index: %d \n' % index)

        snfvo_data = {{inputs.parameters.snfvo_data}}
        sys.stdout.write('snfvo_data: %s \n' % snfvo_data)

        userdata = snfvo_data[mapped_function]
        userdata['pool'] = snfvo_data['upf_pools'][index]
        sys.stdout.write('userdata: %s \n' % userdata)

        with open('/tmp/userdata.txt', 'w') as f:
            json.dump(userdata, f)

    outputs:
      parameters:
      - name: userdata
        valueFrom:
          path: /tmp/userdata.txt

# =============================================================================================================== #
#  - name: instantiate
#    steps:
#    - - name: instantiate-service
#        when: "{{workflow.parameters.sub_operation}} == \"INSTANTIATE_SERVICE\""
#        template: instantiate-service
#
#
#  - name: instantiate-service
#    dag:
#      tasks:
#      - name: get-order-from-catalog
#        templateRef:
#          name: workflow-catalog
#          template: get-order-from-catalog
#        arguments:
#          parameters:
#          - name: order_id
#            value: "{{workflow.parameters.order_id}}"
#
#      - name: trigger-instantiate
#        dependencies: [get-order-from-catalog]
#        template: trigger-instantiate
#        arguments:
#          parameters:
#          - name: related_party
#            value: "{{tasks.get-order-from-catalog.outputs.parameters.related_party}}"
#          - name: order_id
#            value: |
#              # TEST: main is slice order id
#              # sub, is Edge order id
#              [
#                {"uuid": "afc96311-263e-4eb8-ab39-d838fe6b023a"},
#                {"uuid": "e212dd6f-d93a-41c1-80c7-4cbef5a6b2fb", "main": "true"}
#              ]
#          - name: snfvo_data
#            value: |
#              {
#                "userdata_slice": {
#                  "sst": "1",
#                  "sd": "010203",
#                  "core_namespace": "operator-a",
#                  "smf_name": "smf-sample",
#                  "connectedFrom": "gNB1",
#                  "pool": "60.61.0.0/16",
#                  "network_name": "gilan",
#                  "network_master": "ens3",
#                  "network_range": "10.20.0.0/24",
#                  "network_start": "10.20.0.2",
#                  "network_end": "10.20.0.50",
#          
#                  "networks": [
#                      {
#                          "name": "sbi",
#                          "master": "ens3",
#                          "range": "10.100.200.0/24",
#                          "start": "10.100.200.21",
#                          "end": "10.100.200.40"
#                      },
#                      {
#                          "name": "up",
#                          "master": "ens3",
#                          "range": "10.4.2.0/24",
#                          "start": "10.4.2.251",
#                          "end": "10.4.2.253"
#                      }
#                  ]
#                }
#              }
#
#  - name: trigger-snfvo
#    inputs:
#      parameters:
#      - name: related_party
#      # list of orders ({uuid,main},..)
#      - name: order_id
#      - name: snfvo_data
#    steps:
#    - - name: snfvo
#        templateRef:
#          name: instantiate-scaleout-terminate
#          template: snfvo
#        arguments:
#          parameters:
#          - name: related_party
#            value: "{{inputs.parameters.related_party}}"
#          - name: order_id
#            value: {{inputs.parameters.order_id}}
#          - name: snfvo_data
#            value: {{inputs.parameters.snfvo_data}}
#
#    - - name: wait-for-snfvo
#        dependencies: [snfvo]
#        templateRef:
#          name: workflow-base
#          template: consume
#        arguments:
#          parameters:
#          - name: kafka
#            value: "{{workflow.parameters.kafka}}"
#          - name: kafka_topic
#            value: "issm-in-{{workflow.parameters.service_owner}}"
#          - name: msg_id
#            value: "{{steps.snfvo.outputs.parameters.event_uuid}}"
#
#
#  - name: scaleout
#    dag:
#      tasks:
#      - name: success
#        templateRef:
#          name: workflow-base
#          template: success
